**1. Creating tensors**

In [ ]:
import torch

# tensors
t1 = torch.tensor([1, 2, 3])
print(t1, t1.shape)

tensor([1, 2, 3]) torch.Size([3])


In [ ]:
t2 = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(t2, t2.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])


In [ ]:
z = torch.zeros([2, 3])
print(z, z.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.Size([2, 3])


In [ ]:
o = torch.ones([2, 3])
print(o, o.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])


In [ ]:
r = torch.randn([2, 3])
print(r, r.shape)

tensor([[ 1.1580,  0.4918,  1.9540],
        [-2.0194,  2.2181, -0.3537]]) torch.Size([2, 3])


In [ ]:
a1 = torch.arange(0, 10, 2)
print(a1, a1.shape)

tensor([0, 2, 4, 6, 8]) torch.Size([5])


In [ ]:
a2 = torch.linspace(0., 1., steps=5)
print(a2, a2.shape)

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]) torch.Size([5])


**2. Dtypes & casting**

In [ ]:
x = torch.arange(10)
print(x, x.shape, x.dtype)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) torch.Size([10]) torch.int64


In [ ]:
x_float = x.float()
print(x_float.dtype)

torch.float32


In [ ]:
x_float = x.long()
print(x_float.dtype)

torch.int64


**3. Indexing and slicing**

In [ ]:
m = torch.arange(1, 10).reshape(3, 3)
print(m, m.shape)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) torch.Size([3, 3])


In [ ]:
print(m[0])

tensor([1, 2, 3])


In [ ]:
print(m[:, 0])

tensor([1, 4, 7])


In [ ]:
print(m[1: ,1:])

tensor([[5, 6],
        [8, 9]])


**4. Reshaping and dimension ops**

In [ ]:
x = torch.arange(12)
print(x, x.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) torch.Size([12])


In [ ]:
x2 = x.reshape(3, 4)
print(x2, x2.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]) torch.Size([3, 4])


In [ ]:
x3 = x.view(2, 6)
print(x3.shape)

torch.Size([2, 6])


In [ ]:
# Add dimensions
x4 = x.unsqueeze(0)    # shape: (1, 12)
print(x4.shape)

torch.Size([1, 12])


In [ ]:
x5 = x.unsqueeze(1)    # shape: (12, 1)
print(x5.shape)

torch.Size([12, 1])


In [ ]:
# Remove dimensions of size 1
x6 = x5.squeeze()
print(x6.shape)

torch.Size([12])


In [ ]:
# 3D example
t3 = torch.arange(24).reshape(2, 3, 4)
print(t3.shape)

torch.Size([2, 3, 4])


In [ ]:
# Swap dimensions (batch, channels, length) -> (batch, length, channels)
t3_perm = t3.permute(0, 2, 1)
print(t3_perm.shape)

torch.Size([2, 4, 3])


**5. Elementwise ops vs matrix multiplication**

In [ ]:
A = torch.arange(6).reshape(2, 3).float()
B = torch.ones((2, 3))

In [ ]:
print("A:", A, A.shape)
print("B:", B, B.shape)

A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) torch.Size([2, 3])
B: tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.Size([2, 3])


In [ ]:
# Elementwise
C = A + B
print("C:", C.shape)

C: torch.Size([2, 3])


In [ ]:
D = A * B
print("D:", D.shape)

D: torch.Size([2, 3])


In [ ]:
# Matrix multiplication: (2,3) x (3,4) -> (2,4)
M1 = torch.randn(2, 3)
M2 = torch.randn(3, 4)
M3 = torch.matmul(M1, M2)
print(M1.shape, M2.shape, M3.shape)

torch.Size([2, 3]) torch.Size([3, 4]) torch.Size([2, 4])


In [ ]:
# Alternative syntax
M4 = M1 @ M2
print(M4.shape)

torch.Size([2, 4])


**6. Moving tensors to GPU (conceptual habit)**

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

Device: cpu


In [ ]:
x = torch.randn(3, 4)
print("Before:", x.device, x.shape)

Before: cpu torch.Size([3, 4])


In [ ]:
x = x.to(device)
print("After:", x.device, x.shape)

After: cpu torch.Size([3, 4])


In [ ]:
# Make sure operations keep device consistent
y = torch.randn(3, 4, device=device)
z = x + y
print(z.device, z.shape)

cpu torch.Size([3, 4])
